feat: adds prerelease-msvc and fix build-docker actions
Adds a new `prerelease-msvc` action that can be used by microservices to
generate a prelease docker image on pull requests labeled with
`prerelease`.

The build-docker action has been updated to work as expected and publish
images.

diff --git a/build-docker/action.yaml b/build-docker/action.yaml
--- a/build-docker/action.yaml
+++ b/build-docker/action.yaml
@@ -1,68 +1,101 @@
-name: "Docker build & push"
-description: "Publish a new release of the project"
+name: Build & push docker images
+description: Builds and push docker images for the input platform, tags and image version
 inputs:
-  checkout-repo:
+  docker-config-file:
     required: false
-    description: "Perform checkout as first step of action"
-    default: "true"
+    description: Path to the docker config file (defaults to .docker-config.json) Must contain imageName, may contain dockerfile.
+    default: .docker-config.json
+  dockerhub-user:
+    required: true
+    description: username for dockerhub
+  dockerhub-password:
+    required: true
+    description: password for dockerhub
   github-token:
     required: true
-    description: "GitHub token that can checkout the repository as well as create tags/releases against it. e.g. 'secrets.GITHUB_TOKEN'"
-  docker-hub-username:
+    description: Usually secrets.GITHUB_TOKEN
+  artifactory-username:
     required: true
-    description: "Username that can access docker hub"
-  docker-hub-password:
+    description: Artifactory user name usually secrets.ARTIFACTORY_USERNAME
+  artifactory-auth-token:
     required: true
-    description: "Password for username that can access docker hub"
-  docker-hub-repository:
+    description: Artifactory auth token usually secrets.ARTIFACTORY_AUTH_TOKEN
+  image-version:
     required: true
-    description: "Organization/repository within docker hub"
-  docker-hub-image-name:
-    required: true
-    description: "Image name within org/repository within docker hub"
-  docker-context:
+    description: Docker image version
+  image-platform:
+    description: Target platform to build image for (eg. linux/amd64 (default), linux/arm64, etc)
     required: false
-    description: "The directory for docker context"
-    default: .
-
+    default: linux/amd64
+  docker-metadata-tags:
+    description: "'List of tags as key-value pair attributes' See: https://github.com/docker/metadata-action#tags-input"
+    required: false
 outputs:
-  version:
-    description: "Version of the project"
-    value: ${{ steps.release.outputs.version }}
+  image-name:
+    description: Docker image name
+    value: ${{ steps.config.outputs.image-name }}
+  image-with-tag:
+    description: Full image with tag - <image-name>:<image-version>
+    value: ${{ steps.config.outputs.image-name }}:${{ inputs.image-version }}
+
 runs:
-  using: "composite"
+  using: composite
   steps:
-    - name: Checkout
-      uses: actions/checkout@v3
-      if: inputs.checkout-repo
+    - name: Dump GitHub context
+      shell: bash
+      env:
+        GITHUB_CONTEXT: ${{ toJson(github) }}
+      run: echo "$GITHUB_CONTEXT"
+    - id: config
+      shell: bash
+      run: |
+        # if docker-config file does not exist - fail
+        if [ ! -f "${{ inputs.docker-config-file }}" ]; then
+          echo "::error::Docker config file not found: ${{ inputs.docker-config-file }}" && exit 1
+        fi
+        image_name=$(jq -r .imageName ${{ inputs.docker-config-file }})
+        echo "image-name: ${image_name}"
+        echo "image-name=${image_name}" >> $GITHUB_OUTPUT
+        dockerfile=$(jq -r '.dockerfile // "./Dockerfile"' ${{ inputs.docker-config-file }})
+        echo "Dockerfile: ${dockerfile}"
+        echo "dockerfile=${dockerfile}" >> $GITHUB_OUTPUT
+        echo "image-version: ${{ inputs.image-version }}"
+        echo "image-platform: ${{ inputs.image-platform }}"
+        echo "docker-metadata-tags: ${{ inputs.docker-metadata-tags }}"
+    - name: Set up QEMU
+      uses: docker/setup-qemu-action@v2
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v2
+    - name: Login to Docker Hub
+      uses: docker/login-action@v2
       with:
-        fetch-depth: 0
-    - name: Authorize
-      uses: open-turo/action-git-auth@v2
-      with:
-        github-personal-access-token: ${{ inputs.github-token }}
-    - name: Login to docker hub
-      uses: docker/login-action@v1
-      with:
-        username: ${{ inputs.docker-hub-username }}
-        password: ${{ inputs.docker-hub-password }}
+        username: ${{ inputs.dockerhub-user }}
+        password: ${{ inputs.dockerhub-password }}
     - name: Docker meta
       id: meta
-      uses: docker/metadata-action@v3
+      uses: docker/metadata-action@v5
       with:
-        images: ${{ inputs.docker-hub-repository }}/${{ inputs.docker-hub-image-name }}
+        images: |
+          ${{ steps.config.outputs.image-name }}
+        flavor: |
+          latest=false
         tags: |
-          type=ref,event=branch
-          type=ref,event=pr
-          type=semver,pattern={{version}}
-          type=sha
+          ${{ inputs.image-tags }}
     - name: Build and push
-      uses: docker/build-push-action@v2
+      uses: docker/build-push-action@v4
       with:
-        context: ${{ inputs.docker-context }}
+        context: .
+        platforms: ${{ inputs.image-platform }}
+        file: ${{ steps.config.outputs.dockerfile }}
         build-args: |
-          GIT_COMMIT=${GITHUB_SHA}
+          GIT_COMMIT=${{ github.sha }}
           GITHUB_TOKEN=${{ inputs.github-token }}
-        push: false
-        tags: ${{ steps.meta.output.tags }}
-        labels: ${{ steps.meta.output.labels }}
+          ARTIFACTORY_USERNAME=${{ inputs.artifactory-username }}
+          ARTIFACTORY_AUTH_TOKEN=${{ inputs.artifactory-auth-token }}
+          BUILDTIME=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
+          VERSION=${{ inputs.image-version }}
+          REVISION=${{ inputs.image-version }}
+          BRANCH=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.branch'] }}
+        push: true
+        tags: ${{ steps.config.outputs.image-name }}:${{ inputs.image-version }}
+        labels: ${{ steps.meta.outputs.labels }}
